"""
Django settings for elevate project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os 
from pathlib import Path
from .dbsecrets import get_secret

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ttg0l-kmsvjd#o00&2+5ev#n0hp9pquzhz-*9yevy(*a%4&)k$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crm',
    "crispy_forms",
    "crispy_bootstrap5",
    "storages",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = 'bootstrap5'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'elevate.urls' #Pointing to urls.py file under our project

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'elevate.wsgi.application'




# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

MEDIA_URL = 'media/'

MEDIA_ROOT = 'media'

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
AWS_SECRETS = get_secret()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': AWS_SECRETS['db_name'] ,
        'USER': AWS_SECRETS['db_user'],
        'PASSWORD': AWS_SECRETS['db_pass'],
        'HOST': 'rn231194889db.chwlezgyi7rm.eu-west-1.rds.amazonaws.com',  # RDS endpoint
        'PORT': '3306',  # Adjust the port based on your RDS configuration
        'OPTIONS':{
            'charset': 'utf8mb4',
    }
}
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [ BASE_DIR / 'static' ]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#AMAZON S3 PERSONAL COPNFIGURATION

AWS_ACCESS_KEY_ID = 'AKIAV7TA7TPMCSTP5AKY' #Enter your AWS Access Key ID 
AWS_SECRET_ACCESS_KEY = 'RrNxy2GNmLwF3MqTUK8FOBkJXg1iM+lDgNRpjfRZ' #Enter your AWS secret Access Key ID 
# AWS_REGION = 'us-east-1'  # e.g., 'us-east-1'

AWS_STORAGE_BUCKET_NAME = 'cppbuckkron' #S3 Bucket name is added here

#Django 4.2 > Storage configuration for S3

STORAGES = {

    #MANAGING MEDIA FILES
    "default":{
        "BACKEND": "storages.backends.s3boto3.S3StaticStorage",

    },

    #MANAGING CSS and JS FILES
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
    },
}

AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

AWS_S3_FILE_OVERWRITE = False #To prevent clashing of the naming of the uploaded pictures