# Generated by Django 4.2.6 on 2023-10-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0003_profile_thought_delete_review_delete_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="Default1.png", null=True, upload_to=""
            ),
        ),
    ]
