# Generated by Django 4.2.6 on 2023-10-31 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0008_alter_posting_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posting",
            name="profile_pic",
        ),
    ]
