# Generated by Django 4.2.6 on 2023-10-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0009_remove_posting_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="posting",
            name="new_pic",
            field=models.ImageField(
                blank=True, default="Default1.png", null=True, upload_to="images/"
            ),
        ),
    ]
