# Generated by Django 4.2.6 on 2023-11-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0010_posting_new_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="thought",
            name="image",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        ),
    ]
