# Generated by Django 4.2.6 on 2023-11-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0011_thought_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="thought",
            name="price",
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name="Posting",
        ),
    ]
