# Generated by Django 4.2.6 on 2023-11-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0012_thought_price_delete_posting"),
    ]

    operations = [
        migrations.AddField(
            model_name="thought",
            name="house_details",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
