# Generated by Django 4.2.6 on 2023-11-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0013_thought_house_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="Default1.png", null=True, upload_to="media/"
            ),
        ),
        migrations.AlterField(
            model_name="thought",
            name="image",
            field=models.ImageField(
                blank=True, default="Default1.png", null=True, upload_to="media/"
            ),
        ),
    ]
